name: CI

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - run: |
          python -m pip install --upgrade pip
          pip install ruff mutmut pytest pytest-cov cyclonedx-bom
      - run: make lint || true
      - run: make test || true
      - run: make mutation-test
      - run: make coverage-report
      - name: Build release (placeholder)
        run: mkdir -p dist && echo "release-$NEW_VERSION" > dist/release.txt
      - run: make sign-artifacts
      - run: make generate-sbom
      - uses: actions/upload-artifact@v3
        with: { name: dist, path: dist }
