name: CI

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    ### auto‑patch mutation‑test
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run mutation-test
      run: make mutation-test || true
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov mutmut cyclonedx-bom
      - run: make lint || true
      - run: make test || true
      - run: make mutation-test
      - run: make coverage-report
      - run: make sign-artifacts
      - run: make generate-sbom

  perf-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install k6
        run: |
          curl -s https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz | tar -xz
          sudo mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/
      - run: make perf-test
      - uses: actions/upload-artifact@v3
        with:
          name: perf-report
          path: perf/perf_report.txt
