name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run lint and tests
        run: |
          make lint || true
          make test || true
      - name: Build release
        run: make release

  static-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install lint tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run static analysis
        run: make static-analysis

  install-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run cross-platform install tests
        run: |
          bash scripts/test_install_docker.sh

  dynamic-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run dynamic security scan
        run: make dynamic-scan
  mutation-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mutmut pytest pytest-cov
      - name: Run mutation tests
        run: make mutation-test

  coverage-report:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Generate coverage report
        run: make coverage-report
